const HEADERS={"content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type","cache-control":"no-store"};
const employees=[
{id:"strategy-lead",title:"Strategy Lead",terms:["strategy","business","objective","decision","ceo"]},
{id:"research-analyst",title:"Research Analyst",terms:["research","market","competitor","trend","analysis","evidence"]},
{id:"product-lead",title:"Product Lead",terms:["product","feature","roadmap","launch","ux"]},
{id:"engineering-lead",title:"Engineering Lead",terms:["build","code","software","prototype","engineering","technical","api"]},
{id:"growth-operator",title:"Growth Operator",terms:["growth","marketing","campaign","content","brand","seo"]},
{id:"revenue-operator",title:"Revenue Operator",terms:["sales","revenue","lead","buyer","crm","outbound"]},
{id:"governance-lead",title:"Governance Lead",terms:["governance","risk","security","audit","compliance","approval"]},
{id:"project-manager",title:"Project Manager",terms:["project","delivery","operations","coordinate","timeline"]}];
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:HEADERS});
function policy(t){if(/credential.*theft|exfiltrat.*secret|deploy.*malware/i.test(t))return{decision:"deny",reason:"Restricted security pattern."};if(/delete.*production|drop.*database|destroy.*resource|rotate.*all.*keys/i.test(t))return{decision:"review",reason:"Consequential production action requires human approval."};return{decision:"allow",reason:"No restricted pattern matched."}}
function route(t){const w=t.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);const s=employees.map(e=>({employee:e,score:e.terms.reduce((n,x)=>n+(w.includes(x)?2:w.some(y=>y.includes(x)||x.includes(y))?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.employee.id.localeCompare(b.employee.id));return(s.length?s:[{employee:employees[0],score:1}]).slice(0,5)}
export default{async fetch(request){if(request.method==="OPTIONS")return json({},204);const u=new URL(request.url);if(u.pathname==="/api/health")return json({ok:true,service:"aethermesh-runtime-api",version:"2026-10-02"});if(u.pathname==="/api/agents")return json({count:employees.length,agents:employees.map(({id,title})=>({id,title}))});if(u.pathname==="/api/workforce"&&request.method==="POST"){let b={};try{b=await request.json()}catch{return json({error:"invalid_json"},400)}const task=String(b.task||"").trim();if(!task)return json({error:"task_required"},400);const p=policy(task),r=route(task),wf=r.map((x,i)=>({role:x.employee.title,order:i+1,score:x.score,state:i===r.length-1?"approval":"ready"}));return json({ok:true,task,policy:p,routed:r.map(x=>({id:x.employee.id,title:x.employee.title,score:x.score})),workforce:wf,plan:{execution:"dependency-aware-sequential",steps:wf.map((x,i)=>({id:"step-"+(i+1),employee:x.role,dependsOn:i?["step-"+i]:[]}))},evaluation:{policyScore:p.decision==="deny"?0:1,routed:r.length,confidence:Math.min(1,(r[0]?.score||1)/4)}})}return json({error:"not_found"},404)}};